# Apply: kubectl apply -f kubernetes/rawkv.yaml
apiVersion: v1
kind: Service
metadata:
  name: rawkv-lb
  namespace: rawkv
spec:
  type: NodePort
  ports:
  - name: server
    port: 8000
    targetPort: 5640
  selector:
    app: rawkv
---
apiVersion: v1
kind: Service
metadata:
  name: rawkv-hl
  namespace: rawkv
spec:
  selector:
    app: rawkv
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rawkv
  namespace: rawkv
spec:
  serviceName: rawkv-hl
  replicas: 3
  selector:
    matchLabels:
      app: rawkv
  podManagementPolicy: Parallel
  template:
    metadata:
      namespace: rawkv
      labels:
        app: rawkv
    spec:
      containers:
      - name: rawkvsvr
        image: rawkvsvr:latest
        imagePullPolicy: Never  # use image from local docker registry
        env:
        - name: RAWKV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RAWKV_SERVICE_NAME
          value: rawkv-hl
        - name: RAWKV_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RAWKV_RAFT_PORT
          value: "5641"
        command:
        - sh
        - -c
        args:
        - "$GOPATH/bin/rawkvsvr \
          -storageaddr :5640 \
          -raftaddr :5641 \
          -loglevel 0 \
          "
